CREATE DATABASE EasyCook;

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS dish;
CREATE SCHEMA IF NOT EXISTS ingredient;
CREATE SCHEMA IF NOT EXISTS shopping;
CREATE SCHEMA IF NOT EXISTS tag;
CREATE SCHEMA IF NOT EXISTS userinfo;